server:
  port: 8010

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=ems;encrypt=true;trustservercertificate=true;
    username: SA
    password: 123456a@